apiVersion: v1
kind: Service
metadata: 
  name: blog-app
spec: 
  selector: 
    app: blog-app
  ports: 
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
